
#### Integrations
##### ThreatConnect Feed
- Updated the Docker image to: *demisto/python3:3.10.8.37233*.
- Fixed an issue where specifying the *confidence* and *threatAssessScore* parameters caused an error.